---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: nacos
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: nacos
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nacos
  name: nacos-cm
data:
  mysql.db.name: "db.name"
  mysql.host: "mysql.host"
  mysql.port: "mysql.port"
  mysql.user: "mysql.username"
  mysql.password: "mysql.password"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: nacos
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      namespace: nacos
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8snacos
          imagePullPolicy: Always
          image: nacos-server:1.0
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
          # readinessProbe:
          #   httpGet:
          #     port: 8848
          #     path: /nacos/v1/console/health/readiness
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 3
          # livenessProbe:
          #   httpGet:
          #     port: 8848
          #     path: /nacos/v1/console/health/liveness
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 3
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.nacos:8848 nacos-1.nacos-headless.nacos:8848 nacos-2nacos-headless.nacos:8848"
  selector:
    matchLabels:
      app: nacos
